name: Deploy to Faable

on:
  push:
    branches:
      - main # Change to your deployment branch if different

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20' # Or your preferred Node version

      - name: Deploy Backend
        working-directory: ./backend # Change to your exact directory path
        run: npx @faable/faable@latest deploy
